version: "3.5"

services:
  dev-box01:
    image: sporule/dev-box
    container_name: dev-box01
    restart: always 
    ports:
      - "10022:22"
      - "10080:8080"
      - "10000:8000"
    volumes:
      - dev-box01:/root/
    env_file:
      - ./dev-box.env

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    volumes:
      - mongodb01:/data/db

volumes:
  dev-box01:
  mongodb01:

networks:
  default:
    name: dev-boxes
